name: 'Azure Policy Governance Pipeline'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
        - apply
        - destroy

permissions:
  contents: read
  pull-requests: write
  security-events: write
  actions: read 

jobs:
  terraform:
    name: 'Terraform Policy Governance'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # ✅ Azure Login using Service Principal credentials from GitHub Secret
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # ✅ Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # ✅ Terraform Init
    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Format Check
      run: |
        cd terraform
        terraform fmt -check -recursive

    - name: Terraform Validate
      run: |
        cd terraform
        terraform validate

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan -input=false -out=tfplan

    - name: Policy Compliance Check
      run: |
        cd terraform
        echo "Checking for policy resources in plan..."
        terraform show tfplan > plan_output.txt
        if grep -q "azurerm_policy" plan_outpu
