name: Azure Policy Governance Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  contents: read
  pull-requests: write
  security-events: write
  actions: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      env:
        AZURE_LOG_LEVEL: debug

    - run: az account show

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - run: |
        cd terraform
        terraform init

    - run: |
        cd terraform
        terraform fmt -check -recursive

    - run: |
        cd terraform
        terraform validate

    - run: |
        cd terraform
        terraform plan -input=false -out=tfplan

    - run: |
        cd terraform
        echo "Checking for policy resources in plan..."
        terraform show tfplan > plan_output.txt
        if grep -q "azurerm_policy" plan_output.txt; then
          echo "Found policy resources:"
          grep "azurerm_policy" plan_output.txt | head -10
        else
          echo "No policy resources found in plan"
        fi
        rm -f plan_output.txt

    - if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        cd terraform
        terraform apply -auto-approve tfplan

    - if: github.event.inputs.action == 'destroy' && github.event_name == 'workflow_dispatch'
      run: |
        cd terraform
        terraform destroy -auto-approve

    - uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        scan-ref: 'terraform/'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
